In [2]:
%cd ../

/home/dmoreno/pipeline_v4_final/pipeline/training/stamp_classifier/data_acquisition/rubin

In [3]:
import pandas as pd

In [4]:
partitions = pd.read_parquet('./data/processed/partitions/rubin_AGN_vs_VS/partitions.parquet')
partitions

              diaObjectId         diaSourceId class     partition
0      579575874903343200  600390536926855231    VS          test
1      604062136292868201  600390554106200196    VS          test
2      628767818971614718  600456548564074666    VS          test
3      611255003922830083  600408130589294661   AGN          test
4      604064197877171385  600438904835277169    VS          test
...                   ...                 ...   ...           ...
10606  628760397268124016  600425738750918673    VS  validation_4
10607  579576630817594252  600394932961674142    VS  validation_4
10608  628768506166378557  600425736469217492    VS  validation_4
10609  604064129157694674  600390560146522612    VS  validation_4
10610  609789492361954587  600355378865111070    VS  validation_4

[10611 rows x 4 columns]

In [6]:
# Filtrar los datos de test y convertirlos en un diccionario
ids_test_new_tax = set(partitions[partitions["partition"] == "test"].diaObjectId.values)
print(f'Test {len(ids_test_new_tax)}')

# Calcular las proporciones de train y val en cada fold
num_folds = 5 
for fold in range(num_folds):
    num_ids_train = partitions[partitions.partition == f'training_{fold}'].shape[0]
    num_ids_val = partitions[partitions.partition == f'validation_{fold}'].shape[0]
    total = num_ids_train + num_ids_val

    print(f'Fold {fold}: train {num_ids_train} ({(num_ids_train/total) * 100 :.1f}%) - val {num_ids_val} ({(num_ids_val/total) * 100:.1f} %)')

Test 506
Fold 0: train 1616 (80.0%) - val 405 (20.0 %)
Fold 1: train 1617 (80.0%) - val 404 (20.0 %)
Fold 2: train 1617 (80.0%) - val 404 (20.0 %)
Fold 3: train 1617 (80.0%) - val 404 (20.0 %)
Fold 4: train 1617 (80.0%) - val 404 (20.0 %)

In [7]:
counts = partitions.groupby(['partition', 'class']).size().reset_index(name='count')
counts.head(50)

       partition class  count
0           test   AGN     51
1           test    VS    455
2     training_0   AGN    164
3     training_0    VS   1452
4     training_1   AGN    165
5     training_1    VS   1452
6     training_2   AGN    165
7     training_2    VS   1452
8     training_3   AGN    165
9     training_3    VS   1452
10    training_4   AGN    165
11    training_4    VS   1452
12  validation_0   AGN     42
13  validation_0    VS    363
14  validation_1   AGN     41
15  validation_1    VS    363
16  validation_2   AGN     41
17  validation_2    VS    363
18  validation_3   AGN     41
19  validation_3    VS    363
20  validation_4   AGN     41
21  validation_4    VS    363